version: '3.7'

services:

  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - "25:25"
    environment:
      RELAY_HOST: smtp.example.com
      RELAY_PORT: 587
      RELAY_USERNAME: alice@example.com
      RELAY_PASSWORD: secretpassword

  redis:
    image: redis
    ports:
      - 17381:6379

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - server_db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 16433:5432
    networks:
      - default
      - serverdb

  server:
    build:
      context: .
    depends_on:
      - db
      - redis
    volumes:
      - .:/app:cached
    ports:
      - '7005:7005'
    networks:
      - default
      - serverdb

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=node-api.dev.local
    networks:
      - default
      - outside
    depends_on:
      - server

volumes:
  server_db_data:

networks:
  serverdb:
    name: serverdb
    external: true
  outside:
    external: true
    name: nginx-proxy
